import Head from 'next/head'

import {useAuthState} from "react-firebase-hooks/auth"
import {auth} from "./firebase"
import Chat from "../components/Chat.jsx"
import SignIn from '../components/SignIn.jsx'



export default function Home() {
  const [user] = useAuthState(auth)
  return (
<>
      <Head>
        <title> Chat Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div className='parent'>
{user ? <Chat/> : <SignIn/>}
  
  
</div>
</>
  )
}
